# Generated by Django 4.2.7 on 2023-11-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='thanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_mass', models.CharField()),
            ],
        ),
    ]
