# Generated by Django 4.2.7 on 2023-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdio', '0002_thanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='usful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solluda', models.CharField()),
                ('enna', models.CharField()),
                ('pandra', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='thanks',
        ),
        migrations.AddField(
            model_name='nandha',
            name='place',
            field=models.CharField(null=True),
        ),
    ]
