# Generated by Django 4.2.7 on 2023-12-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdio', '0004_nandha_waste_alter_nandha_des'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usful',
            new_name='useful',
        ),
    ]
