# Generated by Django 4.2.7 on 2023-12-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdio', '0005_rename_usful_useful'),
    ]

    operations = [
        migrations.CreateModel(
            name='bro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solluda', models.CharField()),
                ('enna', models.CharField()),
                ('pandra', models.CharField()),
            ],
        ),
    ]
