# Generated by Django 4.2.7 on 2023-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdio', '0006_bro'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bro',
        ),
        migrations.DeleteModel(
            name='nandha',
        ),
        migrations.DeleteModel(
            name='useful',
        ),
    ]
