# Generated by Django 4.2.7 on 2023-12-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdio', '0007_login_record_signup_delete_bro_delete_nandha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_record',
            name='department',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='login_record',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='login_record',
            name='username',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
