# Generated by Django 4.2.7 on 2023-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cdio', '0009_delete_login_record_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8, null=True)),
                ('department', models.CharField(max_length=25, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
