# Generated by Django 4.2.7 on 2023-12-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdio', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('con_password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='login_record',
        ),
    ]
